### PR TITLE
Update pygments.rb

### LINKED ISSUE #110: Update pygments
Can you please update pygments package? Modern version brings much more languages!

### PR DESCRIPTION
**Pull request by verhovsky**
I pinned haml to version 5 in the Gemfile (because version 5 is already in Gemfile.lock and version 6 doesn't seem to work) then I ran

```sh
gem install bundler:1.16.1
bundle update
bundle install
bundle exec middleman build

cd build
python -m http.server

chrome 'http://localhost:8000'
```

Fixes #110 and allows highlighting Zig code (see https://github.com/adambard/learnxinyminutes-docs/issues/4507 and https://github.com/adambard/learnxinyminutes-docs/issues/4536 )

### CODE REVIEW

**Comment by KaneRoot** [comment]
Thanks!

**Comment by verhovsky** [comment]
@adambard ping

**Comment by vendethiel** [comment]
Also interested in this.

**Comment by adambard** [comment]
@verhovsky @vendethiel I find myself apologizing once again for my lack of responsibility for this project.

I propose that we implement the building of this project as a github workflow, to be deployed to a static site hosting vendor of choice. This would put the whole pipeline in the hands of this site's community, though I would of course be happy to continue hosting it.

The branch `build-github-action` contains a brief attempt, but unfortunately it seems like it might be real work to get building. I'll try to get back to it this week, but I'm open to contributions.

**Comment by verhovsky** [comment]
@adambard I haven't been able to build learnxinyminutes-site using Ruby 3 while working on this either. If you try

```yaml
      - name: Set up Ruby 3.1
        uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: "2.6"
```

it'll probably work.

**Comment by verhovsky** [comment]
@adambard if you accept #114 it should work with Ruby 3.3

**Comment by verhovsky** [comment]
@adambard I think you need something like this

```yaml
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        repository: https://github.com/adambard/learnxinyminutes-docs
        path: learnxinyminutes/source/docs
```

**Comment by verhovsky** [comment]
@adambard I fixed that error in https://github.com/adambard/learnxinyminutes-docs/pull/4873

**Pull request merged**
