### PR TITLE
Add dark theme

### PR DESCRIPTION
**Pull request by divayprakash**
Dark theme for the entire site using HTML5 `localStorage` for persistence. Adds theme picker buttons in right top corner below language highlight selector on index page and below share button on doc pages. All text is i18n. Buttons are styled similar to language slugs.

Light theme (same as before, only change is theme picker in right top corner):
image
image

Dark theme (uses Monokai theme for syntax highlighting):
image
image

Styled language highlight selector:
image
image

Styled theme selection and share buttons:
image
image

### CODE REVIEW

**Comment by divayprakash** [comment]
@adambard Please review!

**Comment by adambard** [comment]
Looks great so far, thanks! I'll have to take some time to see myself how switching themes feels, but your implementation seems promising.

My only immediate feedback is all color-based:

* The blue for links is a bit difficult to read against the black bg -- it could be made a bit lighter, I think. (Try `#49c` perhaps?)
* I usually like to stay away from pure `#000` for reasons I can't articulate, but I'm open to contrary opinions. Between `#000` and, say, `#11111a`, which do you think works better?

**Comment by divayprakash** [comment]
> The blue for links is a bit difficult to read against the black bg -- it could be made a bit lighter, I think. (Try #49c perhaps?)

Done! I also lightened the color for visited links from `#551a8b` to `##7d26cd`.

> I usually like to stay away from pure #000 for reasons I can't articulate, but I'm open to contrary opinions. Between #000 and, say, #11111a, which do you think works better?

`#11111a` works better with the theme overall so I've switched to that.

**Comment by divayprakash** [comment]
@adambard This is as close as I could get to some clean code. I've also reduced FOUC as much as possible.

**Comment by adambard** [comment]
@divayprakash I made a few changes and I think I managed to eliminate the FOUC (well, on my machine anyhow):

* Changed the mechanism to always include styles for dark mode, but apply them only if the `html` element has the class "dark"
* Moved the JS back into the head, so it's ready just as soon as the CSS is done, and changed it to swap the html element's class rather than the css file (this prevents a delay caused by loading the stylesheet)
* Refactored the css while I was at it to compile to a single file -- this should be better for load times than multiple requests
* Made a few color tweaks and added a css transition for fun.

My changes are all in 927e6c6c1fe5b514d16c0885c075570419efb31d -- could you give that a review when you have a moment?

(I had to make a new branch on this repo because I can't push to yours, so #55 (`divayprakash-dark-theme`) is a duplicate of this PR. Feel free to just pull from that and push back here.)

**Comment by divayprakash** [comment]
> My changes are all in 927e6c6 -- could you give that a review when you have a moment?

Working on it now!

> I had to make a new branch on this repo because I can't push to yours, so #55 (divayprakash-dark-theme) is a duplicate of this PR.

Sorry about that, I forgot to click 'allow edits from maintainers'. Fixed now.

**Comment by divayprakash** [comment]
32edfa8 corrects the function name in button `onclick` so they work again (only on the index page).

**Comment by divayprakash** [comment]
The buttons look cut off on the bottom side to me (may be a color issue) -
image

I've fixed that in 0449da0. Now it looks like this -
image

**Comment by divayprakash** [comment]
@adambard I think that about wraps this up!

**Comment by adambard** [comment]
Perfect, well done! That's going live now.

**Pull request merged**
