### PR TITLE
Nixify so it can be easily developed on in Nix

### PR DESCRIPTION
**Pull request by candeira**
To be commited simultaneously with https://github.com/adambard/learnxinyminutes-docs/pull/3616

### CODE REVIEW

**Comment by candeira** [comment]
Hi @adambard, it looks to me like you merged the instructions on adambard/learnxinyminutes-docs but not the code on this here pull request.

**Comment by divayprakash** [comment]
> Hi @adambard, it looks to me like you merged the instructions on adambard/learnxinyminutes-docs but not the code on this here pull request.

Sorry that's my bad! I merged the code on the docs repo but somehow missed there was a merge required here first.

**Comment by candeira** [comment]
No worries, and thanks!

**Comment by adambard** [comment]
Thanks for your enthusiasm, but I'm afraid I can't get behind this change -- things are rickety enough around here without supporting a second stack.

**Pull request closed without merging**
