### PR TITLE
Use Pygments highlighting instead of Rouge for 2x+ more languages supported...

### PR DESCRIPTION
**Pull request by samcv**
and at least 35%+ more based on our full list of languages the docs use.

### CODE REVIEW

**Comment by vendethiel** [comment]
:+1:

**Comment by adambard** [comment]
Awesome, I'll test this out on the server tonight or tomorrow and deploy (pending said test)

**Comment by samcv** [comment]
@adambard did you ever test this out? Thanks :smile:

**Comment by adambard** [comment]
I never did :X. Sorry, I probably won't realistically get to this until I
have some free time during Christmas break

**Comment by samcv** [comment]
That's perfectly fine, just checking in.

**Comment by adambard** [comment]
Merged, finally. Sorry I took so long, turns out it just worked first try. Thanks so much, the autodetection of pygments is already doing some real work.

**Pull request merged**
