### PR TITLE
Add whitespace

### PR DESCRIPTION
**Pull request by aloisdg**

### CODE REVIEW

**Comment by adambard** [comment]
Is this a french thing I don't know about? I've never seen a space before a colon or a question mark before.

**Comment by adambard** [comment]
Upon further reading it turns out there is. The more you know!

**Comment by aloisdg** [comment]
Glad to be helpful!

**Comment by vendethiel** [comment]
This is how you see I've been writing too much english! That's perfectly correct, thanks @aloisdg.

**Pull request merged**
