### PR TITLE
Added Czech (cs_cz) translation

### PR DESCRIPTION
**Pull request by scheras**

### CODE REVIEW

**Comment by vojtasvoboda** [comment]
#17 :-)

**Comment by adambard** [comment]
In fairness the other one got here first. Care to give it a read-over? https://github.com/adambard/learnxinyminutes-site/blob/master/data/i18n.yaml

**Comment by scheras** [comment]
Sorry, i didn't see. The first translation is ok.

**Comment by vojtasvoboda** [comment]
:+1:

**Pull request closed without merging**
